name: Mildly Interesting Facts
on:
  schedule:
    - cron: "0 0 1 * *" 
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Mildly interesting facts
        uses: f-allian/metrics@master
        with:
          filename: images/metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_from: 900
          plugin_habits_facts: yes
          plugin_habits_charts: yes  
          config_timezone: Europe/London
